#!/bin/bash

echo ==========================================================================
echo "  Building BeagleScopeJoystic"
echo "  g++ -O2 -Wall BeagleScopeJoystic.cpp -o BeagleScopeJoystic"
echo ----------------compiling-------------------------------------------------
g++ -O2 -Wall BeagleScopeJoystic.cpp SimpleGPIO.cpp -o BeagleScopeJoystic -Wformat-extra-args
echo ------------------done----------------------------------------------------
echo ==========================================================================