#!/bin/bash

echo ==========================================================================
echo "Building the Simple GPIO Example - See derekmolloy.ie"
echo "g++ -O2 -Wall BeagleScopeJoystic.cpp -o BeagleScopeJoystic"
echo --------------------------------------------------------------------------
g++ -O2 -Wall BeagleScopeJoystic.cpp -o BeagleScopeJoystic
echo ==========================================================================